### ISSUE TITLE
jupyter execute fails for certain notebooks

### ISSUE THREAD

**Issue by callmephilip** [rgbkrk/denotebooks#8]
Trying to run `jupyter execute` on some notebooks fail with smth along these lines (complete log [here](https://github.com/callmephilip/denotebooks/actions/runs/12275311144/job/34250099498)):

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/bin/jupyter-execute", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_core/application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/cli.py", line 161, in initialize
    self.run_notebook(path)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/cli.py", line 215, in run_notebook
    client.execute()
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1005, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 787, in _async_poll_for_reply
    await asyncio.wait_for(task_poll_output_msg, self.iopub_timeout)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/tasks.py", line [48](https://github.com/callmephilip/denotebooks/actions/runs/12275311144/job/34250099498#step:8:49)9, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 817, in _async_poll_output_msg
    self.process_message(msg, cell, cell_index)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1103, in process_message
    display_id = content.get("transient", {}).get("display_id", None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

repro here: https://github.com/rgbkrk/denotebooks/pull/7

**Comment by rgbkrk** [comment]
Interesting... That's likely an issue in the jupyter library Deno uses that I _think_ I fixed but haven't brought over to Deno yet. https://github.com/runtimed/runtimed/pull/165

**Comment by callmephilip** [comment]
Current workaround is to run these through [nbclient directly](https://github.com/callmephilip/jurassic/blob/main/.jurassic/runnb.py) using [this fork](https://github.com/callmephilip/nbclient/tree/fix/transient-set-to-none)

**Comment by rgbkrk** [comment]
If you've got a PR for nbclient, I can merge that over there. However I'm guessing this notebook doesn't pass validation (even though I made it in either VS Code or jupyterlab at the time).

**Comment by callmephilip** [comment]
> Approved your PR [jupyter/nbclient#322](https://github.com/jupyter/nbclient/pull/322). However I'm guessing this notebook doesn't pass validation (even though I made it in either VS Code or jupyterlab at the time).

thanks for expediting things @rgbkrk!
